# Generated by Django 5.1.7 on 2025-05-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_account_gbp_user_account_usd_user_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='routing_usd',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sort_code_gbp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
