# Generated by Django 5.1.7 on 2025-05-23 20:52

import userauths.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_routing_usd_user_sort_code_gbp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userauths.models.UserManager()),
            ],
        ),
    ]
