pipeline{
    agent any
    stages {
        stage('Setup Python Virtual Environment') {
            steps {
                // Change directory to where the script and Jenkinsfile are
                dir('currency_converter') {
                    echo 'Setting Up Venv...'
                    sh '''
                    chmod +x envsetup.sh
                    ./envsetup.sh
                    '''
                }
            }
        }
        stage('Setup Gunicorn Server') {
            steps {
                // Change directory to where the script is
                dir('currency_converter') {
                    echo 'Starting Up Gunicorn...'
                    sh '''
                    chmod +x gunicorn.sh
                    ./gunicorn.sh
                    '''
                }
            }
        }
        stage('Setup Nginx Server') {
            steps {
                // Change directory to where the script is
                dir('currency_converter') {
                    echo 'Starting Up Nginx...'
                    sh '''
                    chmod +x nginx.sh
                    ./nginx.sh
                    '''
                    echo 'Deploying...' // Assuming deployment steps might also need this context
                }
            }
        }
    }
    post {
        always {
            echo 'This will always run after the stages.'
        }
    }
}